token:
    'your token here'
steamkey:
    'your steam api key here'
MALAuth:
    username:
        'mal username here'
    password:
        'mal password here'
owner:
    '224238284593823745'
osukey:
    'osu api key here'