#"True" to enable, "False" to disable.
enable_command_logging:
    "False"
token:
    'Your token'
steamkey:
    'Your Steam API key'
MALAuth:
    username:
        'MAL Username'
    password:
        'MAL Password'
owner:
    'Owner User Discord ID'
osukey:
    'osu! API key'
prefix:
    'r%'